version: "3"

x-airflow-common:
  &airflow-common
  build:
      context: .
      dockerfile: ./airflow_service/Dockerfile
  image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}

services:

  airflow-webserver:
    <<: *airflow-common
    command: webserver

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: version

  rmq_producer_1:
    tty: true
    build:
        context: .
        dockerfile: ./rabbit_producer/Dockerfile
    container_name: rmq_producer_1

  rmq_producer_2:
    tty: true
    build:
        context: .
        dockerfile: ./rabbit_producer/Dockerfile
    container_name: rmq_producer_2

  rmq_producer_3:
    tty: true
    build:
        context: .
        dockerfile: ./rabbit_producer/Dockerfile
    container_name: rmq_producer_3

  rmq_consumer_1:
    tty: true
    container_name: rmq_consumer_1
    build:
        context: .
        dockerfile: ./rabbit_consumer/Dockerfile

  rmq_consumer_2:
    tty: true
    container_name: rmq_consumer_2
    build:
        context: .
        dockerfile: ./rabbit_consumer/Dockerfile 

  fastapi:
    build:
        context: .
        dockerfile: ./fastapi_service/Dockerfile