global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: airflow
    static_configs:
      - targets:
        - airflow-webserver:8080
  - job_name: rabbit
    static_configs:
      - targets:
        - rabbitmqServer:15692