name: Test|Build|Publish image to DH 
on:
  push:
   branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ./for_pip_install/rmq_custom_pack-0.0.1-py3-none-any.whl
      - name: setup variables
        run: |
          TMPFILE=$(tempfile --directory ~/ --prefix dh_pass_ --suffix .txt)
          echo "${{ secrets.DOCKER_HUB_USER }}" > $TMPFILE
      - name: test
        run: |
          pytest ./rabbit_producer/test_producer.py
          pytest ./rabbit_consumer/test_consumer.py
      - name: build image
        run: |
          docker compose build 
      - name: push to docker hub
        run: |
          cat $TMPFILE | docker login --username ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USER }}/PSTE_service:latest
