name: Test|Build|Publish image to DH 
on:
  push:
   branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ./for_pip_install/rmq_custom_pack-0.0.1-py3-none-any.whl
      - name: Setup variables
        run: |
          TMPFILE=$(tempfile --directory ~/ --prefix dh_pass_ --suffix .txt)
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" > $TMPFILE
      - name: Test
        run: |
          pytest ./rabbit_producer/test_producer.py
          pytest ./rabbit_consumer/test_consumer.py
      - name: Build image
        run: |
          docker image prune
          docker images
          docker compose -f docker-compose-build.yml build
          docker images
      - name: Push to docker hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker tag vbr_bak_nasa_turbofans_project-fastapi ${{ secrets.DOCKER_HUB_USER }}/pste-service-fastapi:v1-release
          docker tag vbr_bak_nasa_turbofans_project-rmq_producer_1 ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-1:v1-release
          docker tag vbr_bak_nasa_turbofans_project-rmq_producer_2 ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-2:v1-release
          docker tag vbr_bak_nasa_turbofans_project-rmq_producer_3 ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-3:v1-release
          docker tag vbr_bak_nasa_turbofans_project-rmq_consumer_1 ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-consumer-1:v1-release
          docker tag vbr_bak_nasa_turbofans_project-rmq_consumer_2 ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-consumer-2:v1-release
          docker tag extending_airflow ${{ secrets.DOCKER_HUB_USER }}/pste-service-airflow:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-fastapi:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-1:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-2:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-producer-3:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-consumer-1:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-rmq-consumer-2:v1-release
          docker push ${{ secrets.DOCKER_HUB_USER }}/pste-service-airflow:v1-release
